name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install jq
        run: sudo apt-get install jq
        
      - name: Check GitHub Pages status
        run: |
          REPO_OWNER="yourusername"
          REPO_NAME="your-repo-name"
          BRANCH="gh-pages"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/deployments?environment=github-pages&sha=${BRANCH}"
          
          # Check if there are any ongoing deployments
          response=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" ${API_URL})
          if [[ -z "$response" ]]; then
            echo "No response from GitHub API. Proceeding with publishing."
          else
            in_progress=$(echo "$response" | jq -r '.[0].status')
            if [[ "$in_progress" == "in_progress" ]]; then
              echo "GitHub Pages deployment is in progress. Waiting for 1 minute before retrying."
              sleep 60
            else
              echo "No ongoing deployment. Proceeding with publishing."
            fi
          fi

          
      - name: Generate Sample File
        run: echo "Hello, GitHub Pages!" > index.html
        
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'
