name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get GitHub Pages status
        run: |
          REPO_OWNER="GovardhanKanala"
          REPO_NAME="nova"
          BRANCH="gh-pages"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/deployments?environment=github-pages&sha=${BRANCH}"
          
          # Save the response to a temporary file
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" ${API_URL} > response.json
          
      - name: Check GitHub Pages status
        run: |
          # Read the response from the temporary file
          response=$(cat response.json)
          
          if [[ -z "$response" ]]; then
            echo "No response from GitHub API. Proceeding with publishing."
          else
            in_progress=$(echo "$response" | jq -r '.[0].status // empty')
            if [[ -z "$in_progress" ]]; then
              echo "No ongoing deployment. Proceeding with publishing."
            elif [[ "$in_progress" == "in_progress" ]]; then
              echo "GitHub Pages deployment is in progress. Waiting for 1 minute before retrying."
              sleep 60
            else
              echo "Unexpected status. Proceeding with publishing."
            fi
          fi

      - name: Generate Sample File
        run: echo "Hello, GitHub Pages!" > index.html
        
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'
