name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if previous publishing is in progress
        id: check_publishing
        run: |
          if [ -f .github/PUBLISH_IN_PROGRESS ]; then
            echo "Another publishing operation is in progress. Retrying..."
            exit 78 # Exit with a special code to trigger a retry
          fi
      - name: Set flag to indicate publishing in progress
        if: ${{ steps.check_publishing.outcome != 'success' }} # Only set the flag if it's not in progress
        run: touch .github/PUBLISH_IN_PROGRESS
      - name: Generate Sample File
        run: |
          echo "Hello, GitHub Pages! Generated at $(date)" > index.html
        
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'

      - name: Cleanup after publishing
        run: rm -f .github/PUBLISH_IN_PROGRESS
