name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  deploy:
    name: Deploy Pages if no running jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate no running jobs
        id: validate_jobs
        run: |
          jobs=$(gh run list --status=in_progress --workflow=pages-build-deployment | wc -l)
          if [[ $jobs -gt 0 ]]; then
            echo "There are running jobs. Waiting before retrying..."
            sleep 300  # Adjust wait time as needed
            exit 1
          fi
          echo "No running jobs. Proceeding with deployment."
        env:
          GH_TOKEN: ${{ secrets.GITHUBTOKEN }}  # Fixed typo in secret name

      - name: Deploy GitHub Pages
        if: steps.validate_jobs.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}  # Fixed typo in secret name
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'
