name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2        
        
      - name: Check GitHub Pages status
        id: check_pages_status
        run: |
          REPO_OWNER="GovardhanKanala"
          REPO_NAME="nova"
          BRANCH="gh-pages"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/deployments?environment=github-pages&sha=${BRANCH}"
          
          response=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" ${API_URL})
          echo "::set-output name=response::${response}"

      - name: Generate Sample File
        run: echo "Hello, GitHub Pages!" > index.html
        
      - name: Publish to GitHub Pages
        if: steps.check_pages_status.outputs.response == ''
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'
