name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test command
        run: |
           gh run list --status=in_progress --workflow=pages-build-deployment
      - name: Retry Deployment
        run: |
          for ((i=1; i<=5; i++)); do
            if ! gh run list --status=in_progress --workflow=pages-build-deployment; then
              echo "Builds are still running. Waiting for 5 minutes before retrying ($i/5)."
              sleep 300 # Wait for 5 minutes
            else
              echo "No builds are running. Proceeding with deployment."
              break # Exit the loop if no builds are running
            fi
          done
        
      - name: Publish to GitHub Pages
        if: success() # Only run if the previous step was successful
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: 'Publish sample file to GitHub Pages'
